Tarea 2 (23190120)
ManuelLoaizaV/194s2035-unmsm pull request #9
Opened 2024-10-21 02:18 UTC by H9i8l7a6r5y

.

2024-10-28 02:28 UTC, ManuelLoaizaV requested changes
- Tarea 4: OK
- Tarea 5: OK

De casualidad has eliminado la tarea de tu compañero León Vasquez. Revierte eso y actualiza el PR para poder mergear tus tareas.

2024-10-28 03:49 UTC, H9i8l7a6r5y commented
Profesor, ya revertí la eliminación de la tarea de mi compañero .
![Captura de pantalla 2024-10-27 224326](https://github.com/user-attachments/assets/63a764ec-91a7-4a70-9024-9910626b0c76)

2024-12-10 02:16 UTC, ManuelLoaizaV commented
Ok.

2024-12-10 04:00 UTC, ManuelLoaizaV approved these changes
LGTM

2024-12-10 04:00 UTC, merged